### ISSUE TITLE
if "Auto Clean Clipboard" = Enable then run crashed and close

### ISSUE THREAD

**Issue by kit20a** [hashemi-hossein/memory-guardian#24]
Hardware = smartphone Meizu 15 (Android 7.1 = Flyme 7.1.1)
keyboard soft = TouchPad Keyboard
MemoryGuardian last version 1.4.2
-------------------------------------
If you conceal the "Auto Clean Clipboard" = Enable switch
then the program closes and does not work.
When trying to re -start, Memoryguardian closes again.
To remove this switch - only delete the Memoryguardian program and re -install, but it still does not clean the buffer in the TouchPad application.

**Comment by ghost** [comment]
This problem also happens to me, and it only happens on my old Android 6 device (I tested on newer devices and it doesn't happen).

Here is the log if you need it:

```
FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: ara.memoryguardian, PID: 19186
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:209)
	at android.os.Handler.<init>(Handler.java:123)
	at android.content.ClipboardManager$2.<init>(ClipboardManager.java:69)
	at android.content.ClipboardManager.<init>(ClipboardManager.java:69)
	at android.app.SystemServiceRegistry$12.createService(SystemServiceRegistry.java:283)
	at android.app.SystemServiceRegistry$12.createService(SystemServiceRegistry.java:280)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:900)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:849)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:1421)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:638)
	at b1.b.y(SourceFile:8)
	at y1.c.n(SourceFile:61)
	at R1.a.w(SourceFile:9)
	at j2.E.run(SourceFile:113)
	at q2.a.run(SourceFile:96)
	Suppressed: o2.f: [o0{Cancelling}@5a5e523, Dispatchers.Default]
```
